#!/usr/bin/env node
// Vendors everything the film needs so that nothing is fetched at render time:
//   film/vendor/three.module.js + three.core.js   (from node_modules/three)
//   film/fonts/*.woff2 + fonts.css                (from @fontsource packages; woff2 only, heavy weights only)
//   assets/mark.svg, 3.png, 4.png                 (from ../advrtizx-film/assets)
// Run once after `npm install`:  node tools/setup.mjs
// The vendored output IS committed, so a fresh clone renders without running this.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NM = path.join(ROOT, 'node_modules');
const mkdir = (p) => fs.mkdirSync(p, { recursive: true });
const copy = (a, b) => { mkdir(path.dirname(b)); fs.copyFileSync(a, b); };

// ---- three -------------------------------------------------------------------------------------------------------
const V = path.join(ROOT, 'film/vendor');
for (const f of ['three.module.js', 'three.core.js']) copy(path.join(NM, 'three/build', f), path.join(V, f));
copy(path.join(NM, 'three/LICENSE'), path.join(V, 'LICENSE-three.txt'));
console.log('three', JSON.parse(fs.readFileSync(path.join(NM, 'three/package.json'), 'utf8')).version, '-> film/vendor');

// ---- fonts -------------------------------------------------------------------------------------------------------
// [package dir, css file(s) to read, family override]
const FONTS = [
  // display (Latin, Latin Extended, Vietnamese): variable weight 200-900 and width 75-125%
  ['@fontsource-variable/mona-sans', ['wdth.css']],
  // Latin / Cyrillic / Greek / Vietnamese: Noto Sans Black
  ['@fontsource/noto-sans', ['900.css']],
  // Arabic: Noto Kufi Arabic Black
  ['@fontsource/noto-kufi-arabic', ['900.css']],
  ['@fontsource/noto-sans-devanagari', ['900.css']],
  ['@fontsource/noto-sans-thai', ['900.css']],
  ['@fontsource/noto-sans-sc', ['900.css']],
  ['@fontsource/noto-sans-jp', ['900.css']],
  ['@fontsource/noto-sans-kr', ['900.css']],
];
const FD = path.join(ROOT, 'film/fonts');
fs.rmSync(FD, { recursive: true, force: true }); mkdir(FD);
let css = '/* Generated by tools/setup.mjs. Do not edit by hand.\n   Display: Mona Sans Variable (wght 200-900, wdth 75-125). Scripts: Noto Black (900) faces. All SIL OFL 1.1. */\n';
let nFiles = 0, bytes = 0;
for (const [pkg, files] of FONTS) {
  const pdir = path.join(NM, pkg);
  for (const cf of files) {
    const text = fs.readFileSync(path.join(pdir, cf), 'utf8');
    const blocks = text.match(/\/\*[^*]*\*\/\s*@font-face\s*\{[^}]*\}/g) || [];
    for (const b of blocks) {
      if (/font-style:\s*italic/.test(b)) continue;
      const m = b.match(/url\(\.\/files\/([^)]+\.woff2)\)\s*format\('woff2(?:-variations)?'\)/);
      if (!m) continue;
      const file = m[1];
      copy(path.join(pdir, 'files', file), path.join(FD, file)); nFiles++; bytes += fs.statSync(path.join(FD, file)).size;
      const out = b.replace(/src:[^;]*;/, `src: url(${file}) format('woff2');`).replace(/font-display:\s*swap;/, 'font-display: block;');
      css += out + '\n';
    }
  }
  const lic = path.join(pdir, 'LICENSE'); if (fs.existsSync(lic)) copy(lic, path.join(FD, `LICENSE-${pkg.split('/').pop()}.txt`));
}
fs.writeFileSync(path.join(FD, 'fonts.css'), css);
console.log(`fonts: ${nFiles} woff2 files, ${(bytes / 1048576).toFixed(1)} MB -> film/fonts`);

// ---- logo assets ---------------------------------------------------------------------------------------------------
const SRC = path.resolve(ROOT, '../advrtizx-film/assets');
for (const f of ['mark.svg', '3.png', '4.png']) { copy(path.join(SRC, f), path.join(ROOT, 'assets', f)); }
console.log('assets: mark.svg 3.png 4.png');
