#!/usr/bin/env python3
"""score.py - procedural score for the AdvrtizX brand film "TRUE ANGLE" (TREATMENT.md section 5).

    python3 audio/score.py            # render everything + verification
    python3 audio/score.py --no-verify

Pipeline: hitsheet.build() -> synths (19 recipes + WALLS) -> mix.render_buses -> mix.reverb (4 act rooms)
-> mix.buses_to_stems (sidechain, gates, bass-mono) -> mix.master (comp, soft clip, TP limiter, -14 LUFS)
-> public/audio/score.wav (48 kHz / 24-bit / stereo / exactly 2,880,000 samples), public/audio/stems/*.wav,
audio/cue_sheet.md, audio/hits.json.

No samples, no licensed audio: every sound is synthesised with numpy/scipy. Deterministic (seed 345).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import hitsheet as hs  # noqa: E402
import mix  # noqa: E402
from dsp import FPS, N_TOTAL, SPF, SR, f2s  # noqa: E402

ROOT = os.path.dirname(HERE)
OUT_WAV = os.path.join(ROOT, "public", "audio", "score.wav")
OUT_STEMS = os.path.join(ROOT, "public", "audio", "stems")
CUE_SHEET = os.path.join(HERE, "cue_sheet.md")
HITS_JSON = os.path.join(HERE, "hits.json")
SUBTYPE = "PCM_24"


def stem_of(h):
    if h.stem == "logo":
        return "logo"
    if h.stem == "room":
        return "room"
    return mix.STEM_OF[mix.ROUTE[h.inst][0]]


def fmt_frame(f):
    return f"{f:g}"


def write_cue_sheet(hits, info):
    L = []
    A = L.append
    A("# TRUE ANGLE - score cue sheet")
    A("")
    A("Generated by `audio/score.py` (do not edit by hand). 48 kHz stereo, 30 fps: **frame f = f x 1600 samples = f/30 s**; "
      "each hit below starts at sample `round(frame/30*48000)`. 120 BPM: beat = 15 f, bar = 60 f. "
      "Tuning: f0 = 110 Hz, logo chord 330/440/550 Hz (3:4:5).")
    A("")
    A(f"Total hits: **{len(hits)}** (excl. mix events). Measured master: **{info['lufs']:.1f} LUFS integrated**, "
      f"true peak **{info['tp_dbfs']:.2f} dBTP**, file length exactly {N_TOTAL:,} samples (60.000 s).")
    A("")
    A("## Mix events")
    A("")
    A("| frame | time (s) | event |")
    A("|---:|---:|---|")
    for f, txt in ((0, "Act I room: T60 0.35 s"),
                   (330, "Act II room: T60 0.9 s - sends crossfade over one beat (f330-345)"),
                   (900, "Act III room: T60 1.5 s - sends crossfade over one beat (f900-915)"),
                   (1350, "Act IV room: T60 2.6 s - sends crossfade over one beat (f1350-1365)")):
        A(f"| {f} | {f / FPS:.3f} | {txt} |")
    for g0, g1, label, duck in hs.GATES:
        A(f"| {g0} | {g0 / FPS:.3f} | GATE {g0}-{g1} ({g1 - g0} f): {label}; mix muted with a 4 ms fade into the cut, "
          f"reverb tails truncated" + ("; ROOM ducked -6 dB, never cut" if duck else "") + " |")
    A(f"| 820 | {820 / FPS:.3f} | master +3 dB ramp across the acceleration f820-869 (snaps back in the f870 silence) |")
    A(f"| 1785 | {1785 / FPS:.3f} | linear master fade to zero at the last sample (the film's only fade) |")
    A("")
    A("Sidechain: SUB and KNOCK hits duck the PAD bus by up to 3 dB and every reverb return by up to 2 dB "
      "(instant attack, 180 ms release). Everything below 120 Hz is mono.")
    A("")
    A("## Notes and deviations from TREATMENT section 5")
    A("")
    for t in (
        "Output is 24-bit PCM (not 32-bit float) so every player and ffmpeg path reads it; internal processing is float64. "
        "Stems (music / sfx / logo / room) are post-reverb, post-ducking, bass-mono, and carry the master's own gain curve "
        "(compressor x make-up x soft clip x limiter x fade), so they **sum to score.wav** (checked: < -128 dBFS difference).",
        "Master order is HP 28 Hz -> hard-silence gates -> 2:1 compressor (-18 dBFS, 10/120 ms) -> make-up gain -> "
        "tanh(1.2x)/tanh(1.2) soft clip -> look-ahead 4x-oversampled true-peak limiter (ceiling -1.5 dBTP, leaves AAC headroom) -> fade. "
        "The make-up gain is solved so BS.1770 integrated loudness is -14.0 LUFS (own K-weighted meter, cross-checked with ffmpeg ebur128).",
        "Mix-desk trims on top of the recipe peaks: PAD bus +8 dB, SUB -2 dB, SFX +2 dB, ROOM +9 dB (so the bed and the paper's air "
        "are audible on laptop speakers); a 17 kHz air low-pass on all stems (the noise recipes are white); bass-mono below 120 Hz.",
        "PAD: each n x 55 Hz partial also carries a 1/h^2.2 harmonic tail (h = 1..6) so the specified LP sweeps (900 -> 1400 -> 4000 Hz) are audible.",
        "TICK: damped sinusoid + HP noise burst; tau = Q/(pi f) clamped to 3-25 ms unless the recipe gives tau (POLY, S05 cluster). "
        "BELL: band-limited FM (Bessel sidebands, nothing above 16 kHz) + a 2f shimmer partial at -20 dB, +/-1.2 cent L/R detune and a tiny strike tick.",
        "FLAP clusters also fire at 720 / 760 / 800 (all five label rewrites, 3 dB lower than 740 / 780), and every acceleration step flaps all five labels "
        "(first 6 chars at the 6 f steps); flips never cross the f870 dead stop.",
        "POLY densify during the acceleration: grids divide by 2 from f820 and by 3 from f850 (still bar-aligned); voice 5 enters on its own 12 f grid at f804, "
        "the first grid point after f800.",
        "RISER 'ends exactly at 899 / 1349' is implemented literally: the last sample is f899 x 1600 / f1349 x 1600, leaving a one-frame gap before the downbeat; "
        "f1349-1350 is a 1 f hard cut that also kills the Act III tail.",
        "Hits that would fall inside a hard-silence gate are not generated (e.g. the beat SUB at f300); sounding events are cut at the next gate.",
        "The SUB soft pulse runs on every beat from f180 to f435 (cut at f450) and again f1185-1305 with the stair groove; HAT runs f1192.5-1312.5. "
        "Act-send crossfades start on the act frame (f330 / f900 / f1350) and last 15 f.",
        "Reverb rooms are unit-energy stereo IRs of band-split decaying Gaussian noise (HF decays 0.55x, LF 1.25x), 12 ms predelay, 10 early reflections, "
        "LP 7 kHz, HP 150 Hz; measured T60 0.35 / 0.90 / 1.50 / 2.61 s. Sends are per instrument (dry: the `square feet.` cluster and the `9:16.` tick); "
        "room wet level rises per act: -3 / -1.5 / 0 / +2 dB per act. Tails never cross a gate.",
    ):
        A(f"- {t}")
    A("")
    A("## Cue list")
    A("")
    shots = hs.SHOTS
    bounds = [s[1] for s in shots] + [1800]
    hits_sorted = sorted(hits, key=lambda h: (h.frame, h.idx))
    for si, (sid, f0, name) in enumerate(shots):
        f1 = bounds[si + 1]
        act = sum(1 for a in hs.ACT_STARTS if f0 >= a) - 1
        A(f"### {sid} {name} - f{f0}-{f1 - 1} ({f0 / FPS:.3f}-{f1 / FPS:.3f} s) - Act {hs.ACT_NAMES[act]}")
        A("")
        A("| frame | time (s) | sample | sound | stem | picture / note |")
        A("|---:|---:|---:|---|---|---|")
        for h in hits_sorted:
            if f0 <= h.frame < f1:
                A(f"| {fmt_frame(h.frame)} | {h.frame / FPS:.4f} | {h.sample:,} | {hs.describe(h)} | {stem_of(h)} | {h.note} |")
        A("")
    open(CUE_SHEET, "w").write("\n".join(L) + "\n")


def write_hits_json(hits):
    rows = []
    for h in hits:
        p = {k: (list(v) if isinstance(v, tuple) else v) for k, v in h.p.items()}
        rows.append(dict(i=h.idx, frame=h.frame, time_s=round(h.frame / FPS, 5), sample=h.sample, inst=h.inst,
                         stem=stem_of(h), params=p, note=h.note))
    json.dump(dict(fps=FPS, sr=SR, samples=N_TOTAL, gates=[list(g[:3]) for g in hs.GATES], hits=rows),
              open(HITS_JSON, "w"), indent=1)


def export(master_out, stems_out):
    os.makedirs(OUT_STEMS, exist_ok=True)
    assert master_out.shape == (N_TOTAL, 2)
    sf.write(OUT_WAV, master_out, SR, subtype=SUBTYPE)
    for k, v in stems_out.items():
        if np.abs(v).max() > 1.0:
            print(f"  WARNING stem {k} peaks above 0 dBFS ({np.abs(v).max():.3f})")
        sf.write(os.path.join(OUT_STEMS, f"{k}.wav"), np.clip(v, -1.0, 1.0), SR, subtype=SUBTYPE)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-verify", action="store_true")
    args = ap.parse_args(argv)
    t0 = time.time()
    print("1/5 hit sheet")
    hits = hs.build()
    print(f"  {len(hits)} hits")
    print("2/5 synthesis + bus render")
    dry, snd, key = mix.render_buses(hits)
    print("3/5 reverb (one room per act)")
    wet = mix.reverb(snd)
    del snd
    print("4/5 stems (sidechain, gates, bass-mono)")
    stems = mix.buses_to_stems(dry, wet, key)
    del dry, wet
    print("5/5 master + export")
    out, stems_out, info = mix.master(stems)
    export(out, stems_out)
    write_cue_sheet(hits, info)
    write_hits_json(hits)
    print(f"done in {time.time() - t0:.1f}s -> {OUT_WAV}")
    if not args.no_verify:
        import verify
        verify.run()


if __name__ == "__main__":
    main()
